Update web_security.md to reflect current security recommendations
mozilla/infosec.mozilla.org pull request #172
Opened 2023-07-21 17:04 UTC by arroway

Committing updates to this page according to the working doc shared earlier this month (https://docs.google.com/document/d/1PWI02tZ03a2TdWxoUCy5Wsv1LtcUjRDcPcrqxVpHaJY/edit)

2023-07-21 17:21 UTC, gene1wood requested changes

2023-07-21 17:21 UTC, gene1wood commented on docs/guidelines/web_security.md
> +Sites should avoid redirections from HTTP to HTTPS on a different host, as this prevents HSTS from being set.
It may be worth being explicit here saying that a site should redirect from HTTP on site A to HTTP on site B, and then site B should redirect from HTTP on site B to HTTPS on site B

2023-07-21 17:21 UTC, gene1wood commented on docs/guidelines/web_security.md
> +[Maximum risk](/guidelines/risk/standard_levels#standard-risk-levels-definition-and-nomenclature) sites might enable the use of HTTP Public Key Pinning (HPKP). HPKP instructs a user agent to bind a s
I think these uses of the word "must" is part of an attempt to follow the [RFC2119](https://www.ietf.org/rfc/rfc2119.txt) standard. If the goal here is to make public key pinning no longer required for maximum risk sites, better than "might" would be "should"
```suggestion
[Maximum risk](/guidelines/risk/standard_levels#standard-risk-levels-definition-and-nomenclature) sites should enable the use of HTTP Public Key Pinning (HPKP). HPKP instructs a user agent to bind a site to specific root certificate authority, intermediate certificate authority, or end-entity public key. This prevents certificate authorities from issuing unauthorized certificates for a given domain that would nevertheless be trusted by the browsers. These fraudulent certificates would allow an active attacker to MitM and impersonate a website, intercepting credentials and other sensitive data.
```

2023-07-24 13:37 UTC, arroway commented on docs/guidelines/web_security.md
> +[Maximum risk](/guidelines/risk/standard_levels#standard-risk-levels-definition-and-nomenclature) sites might enable the use of HTTP Public Key Pinning (HPKP). HPKP instructs a user agent to bind a s
'Should' doesn't sound right here, as pinning is not recommended. It 'might' be recommended for some websites in some case, otherwise other website 'should not' use it.

2023-07-24 13:38 UTC, arroway commented on docs/guidelines/web_security.md
> +Sites should avoid redirections from HTTP to HTTPS on a different host, as this prevents HSTS from being set.
I'm not sure I understand what's the added information in this reformulation?

2023-07-26 21:53 UTC, gene1wood commented on docs/guidelines/web_security.md
> +Sites should avoid redirections from HTTP to HTTPS on a different host, as this prevents HSTS from being set.
Something like this @arroway 

```suggestion
Sites should avoid redirections from HTTP to HTTPS on a different host, as this prevents HSTS from being set. Instead, for example, first redirect from http://example.com/ to https://example.com/ and then in a second redirect, redirect from https://example.com/ to https://example.org/
```

2023-07-26 21:56 UTC, gene1wood commented on docs/guidelines/web_security.md
> +[Maximum risk](/guidelines/risk/standard_levels#standard-risk-levels-definition-and-nomenclature) sites might enable the use of HTTP Public Key Pinning (HPKP). HPKP instructs a user agent to bind a s
@arroway If we're not saying that it `must` or `should` be used, could we just remove this entire paragraph about key pinning?

Or if we want to keep this in and show that it's optional, let's use the [RFC2119](https://www.ietf.org/rfc/rfc2119.txt) term `may` instead of `might`

2023-07-27 14:47 UTC, arroway commented on docs/guidelines/web_security.md
> +[Maximum risk](/guidelines/risk/standard_levels#standard-risk-levels-definition-and-nomenclature) sites might enable the use of HTTP Public Key Pinning (HPKP). HPKP instructs a user agent to bind a s
In that case, "may" sounds more appropriate for this case.

2023-07-27 14:47 UTC, closed without merging

2023-07-27 14:53 UTC, arroway commented
Closing this PR to squash commits properly and will re-open a clean PR  (I was lazy before and only use GH UI).

2023-07-27 15:29 UTC, gene1wood commented
Looks good!